(function(root,factory){const cards=factory();if(typeof module==='object'&&module.exports)module.exports=cards;else root.RadarCards=cards;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 return [
 ['fechas_cortes','¿Qué ocurrió el 31 de octubre de 1978?','Las Cortes Generales aprobaron la Constitución.','Cortes: aprueban.'],
 ['fechas_pueblo','¿Qué ocurrió el 6 de diciembre de 1978?','El pueblo español ratificó la Constitución en referéndum.','Pueblo: ratifica.'],
 ['fechas_rey','¿Qué ocurrió el 27 de diciembre de 1978?','El Rey sancionó y promulgó la Constitución.','Rey: sanciona y promulga.'],
 ['fechas_boe','¿Qué ocurrió el 29 de diciembre de 1978?','La Constitución se publicó en el BOE y entró en vigor.','Publicación y entrada en vigor: la misma fecha.'],
 ['estructura_articulos','¿Cuántos artículos y títulos numerados tiene la Constitución?','Tiene 169 artículos y diez títulos numerados, además del Título Preliminar.','No cuentes el Título Preliminar como uno de los diez numerados.'],
 ['preambulo','¿Tiene el Preámbulo valor normativo directo?','El Preámbulo no tiene valor normativo directo, aunque sirve para interpretar la Constitución.','Explica las intenciones: no es un título de artículos.'],
 ['preliminar','¿Qué artículos comprende el Título Preliminar?','El Título Preliminar comprende los artículos 1 a 9.','El artículo 10 abre el Título I.'],
 ['art14_igualdad','¿Qué reconoce el artículo 14?','Los españoles son iguales ante la ley, sin discriminación por nacimiento, raza, sexo, religión, opinión ni otra condición o circunstancia personal o social.','Igualdad ante la ley y prohibición de discriminación.'],
 ['art15_vida','¿Qué derechos reconoce el artículo 15 y qué tratos prohíbe?','Todos tienen derecho a la vida y a la integridad física y moral; nadie puede sufrir tortura ni penas o tratos inhumanos o degradantes.','Esta tarjeta se centra en los derechos y la prohibición de tortura.'],
 ['art1_estado','¿Cómo define España el artículo 1.1?','España se constituye en un Estado social y democrático de Derecho.','Aprende la expresión completa.'],
 ['art1_valores','¿Cuáles son los valores superiores del artículo 1.1?','Los valores superiores son la libertad, la justicia, la igualdad y el pluralismo político.','Son cuatro.'],
 ['art1_soberania','¿Dónde reside la soberanía nacional?','La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado.','Artículo 1.2.'],
 ['art1_forma','¿Cuál es la forma política del Estado español?','La forma política del Estado español es la Monarquía parlamentaria.','Artículo 1.3.'],
 ['art2','¿Qué tres ideas reúne el artículo 2?','La indisoluble unidad de la Nación española, la autonomía de las nacionalidades y regiones y la solidaridad entre todas ellas.','Unidad, autonomía y solidaridad.'],
 ['art3','¿Qué establece el artículo 3.1 sobre el castellano?','El castellano es la lengua española oficial del Estado; todos los españoles tienen el deber de conocerla y el derecho a usarla.','No confundas deber de conocer con derecho a usar.'],
 ['art4','¿Cómo describe el artículo 4.1 la bandera de España?','Tiene tres franjas horizontales: roja, amarilla y roja; la amarilla es de doble anchura que cada roja.','La franja central ocupa la mitad de la anchura total.'],
 ['art5','¿Cuál es la capital del Estado?','La capital del Estado es la villa de Madrid.','Artículo 5.'],
 ['art6','¿Qué exige el artículo 6 a los partidos políticos?','Los partidos expresan el pluralismo político; su estructura interna y su funcionamiento deben ser democráticos.','Su creación y actividad son libres dentro del respeto a la Constitución y a la ley.'],
 ['art7','¿Qué organizaciones regula el artículo 7?','Los sindicatos de trabajadores y las asociaciones empresariales, que defienden y promueven los intereses económicos y sociales que les son propios.','Su estructura interna y funcionamiento deben ser democráticos.'],
 ['art8','¿Qué misión tienen las Fuerzas Armadas según el artículo 8?','Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional.','Son tres misiones.'],
 ['art9_1','¿A qué están sujetos los ciudadanos y los poderes públicos?','A la Constitución y al resto del ordenamiento jurídico.','Artículo 9.1.'],
 ['art9_3','¿Qué garantías recoge el artículo 9.3?','Legalidad, jerarquía normativa, publicidad de las normas, irretroactividad de disposiciones sancionadoras no favorables o restrictivas de derechos individuales, seguridad jurídica, responsabilidad e interdicción de la arbitrariedad de los poderes públicos.','No afirma que todas las normas sean irretroactivas.'],
 ['titulo1','¿Qué comprende el Título I?','El Título I, «De los derechos y deberes fundamentales», comprende los artículos 10 a 55.',''],
 ['titulo2','¿Qué comprende el Título II?','El Título II, «De la Corona», comprende los artículos 56 a 65.',''],
 ['titulo3','¿Qué comprende el Título III?','El Título III, «De las Cortes Generales», comprende los artículos 66 a 96.',''],
 ['titulo4','¿Qué comprende el Título IV?','El Título IV, «Del Gobierno y de la Administración», comprende los artículos 97 a 107.',''],
 ['titulo5','¿Qué comprende el Título V?','El Título V, «De las relaciones entre el Gobierno y las Cortes Generales», comprende los artículos 108 a 116.',''],
 ['titulo6','¿Qué comprende el Título VI?','El Título VI, «Del Poder Judicial», comprende los artículos 117 a 127.','La Justicia: Poder Judicial.'],
 ['titulo7','¿Qué comprende el Título VII?','El Título VII, «Economía y Hacienda», comprende los artículos 128 a 136.',''],
 ['titulo8','¿Qué comprende el Título VIII?','El Título VIII, «De la organización territorial del Estado», comprende los artículos 137 a 158.',''],
 ['titulo9','¿Qué comprende el Título IX?','El Título IX, «Del Tribunal Constitucional», comprende los artículos 159 a 165.',''],
 ['titulo10','¿Qué comprende el Título X?','El Título X, «De la reforma constitucional», comprende los artículos 166 a 169.',''],
 ['art27_educacion','¿Cómo es la enseñanza básica según el artículo 27.4?','La enseñanza básica es obligatoria y gratuita.','No afirma que toda enseñanza sea obligatoria.'],
 ['art17_detencion','¿Cuál es el límite de la detención preventiva del artículo 17.2?','Solo puede durar el tiempo estrictamente necesario y, como máximo, 72 horas; después, el detenido debe quedar en libertad o a disposición judicial.','Las 72 horas son un máximo, no una duración obligatoria.'],
 ['art24_tutela','¿Qué protege el artículo 24.1?','El derecho de todas las personas a la tutela efectiva de jueces y tribunales en sus derechos e intereses legítimos, sin indefensión.','Tutela judicial efectiva.'],
 ['tc_fuera','¿Forma el Tribunal Constitucional parte del Poder Judicial?','No; el Tribunal Constitucional es el intérprete supremo de la Constitución y no forma parte del Poder Judicial.','No es el tribunal superior de todos los jueces.'],
 ['art18_intimidad','¿Qué tres derechos garantiza el artículo 18.1?','El derecho al honor, a la intimidad personal y familiar y a la propia imagen.','El domicilio y las comunicaciones se regulan en otros apartados del artículo 18.'],
 ['art23_participacion','¿Cómo pueden participar los ciudadanos en los asuntos públicos?','Directamente o por representantes libremente elegidos en elecciones periódicas por sufragio universal.','Artículo 23.1.'],
 ['art31_deber','¿Qué deber establece el artículo 31.1?','Todos contribuirán al sostenimiento de los gastos públicos de acuerdo con su capacidad económica mediante un sistema tributario justo.','Se inspira en igualdad y progresividad y no tendrá alcance confiscatorio.'],
 ['disposiciones','¿Cuántas disposiciones hay y en qué orden aparecen?','Cuatro adicionales, nueve transitorias, una derogatoria y una final.','4-9-1-1: A-T-D-F.']
 ].map(([id,q,a,t])=>Object.freeze({id,q,a,t}));
});
